# Generated by Django 5.2 on 2025-04-14 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ed', models.DateField(auto_now_add=True)),
                ('updated_ed', models.DateField(auto_now=True)),
                ('total_duration', models.IntegerField()),
                ('course_start_time', models.DateField()),
                ('course_end_time', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PositionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=3, unique=True)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=3, unique=True)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='live_place_address',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='salary_pay',
        ),
        migrations.AddField(
            model_name='teacher',
            name='staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.staff'),
        ),
        migrations.AddField(
            model_name='workersalarywaitedpay',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiting_salaries', to='user_auth.staff'),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_group',
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ed', models.DateField(auto_now_add=True)),
                ('updated_ed', models.DateField(auto_now=True)),
                ('mentor_group', models.ManyToManyField(related_name='mentors', to='user_auth.group')),
                ('staff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.staff')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ed', models.DateField(auto_now_add=True)),
                ('updated_ed', models.DateField(auto_now=True)),
                ('course_cost_per_week', models.IntegerField()),
                ('course_total_cost', models.IntegerField()),
                ('course_name', models.CharField(max_length=90)),
                ('course_descriptions', models.TextField(max_length=150)),
                ('students', models.ManyToManyField(blank=True, related_name='courses', to='user_auth.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='user_auth.teacher')),
                ('course_duration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='user_auth.courseduration')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='user_auth.mentor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_auth.positionlevel'),
        ),
        migrations.AddField(
            model_name='courseduration',
            name='work_days',
            field=models.ManyToManyField(related_name='course_durations', to='user_auth.studyday'),
        ),
        migrations.AddField(
            model_name='staff',
            name='work_days',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='user_auth.workday'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_group',
            field=models.ManyToManyField(related_name='teachers', to='user_auth.group'),
        ),
    ]
