# Generated by Django 5.2 on 2025-04-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_room_remove_mentor_mentor_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayedProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ed', models.DateField(auto_now_add=True)),
                ('updated_ed', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='rom_number',
            new_name='rom_numb',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='rom_num',
            new_name='rom_number',
        ),
    ]
