# Generated by Django 5.2 on 2025-04-16 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_payedprogram_rename_rom_number_lesson_rom_numb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyedForWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ed', models.DateField(auto_now_add=True)),
                ('updated_ed', models.DateField(auto_now=True)),
                ('card_number', models.IntegerField(max_length=16, unique=True)),
                ('work_time', models.DateTimeField(auto_now_add=True)),
                ('balance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_auth.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PayedProgram',
        ),
    ]
