# Generated by Django 5.2 on 2025-04-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_pyedforworker_delete_payedprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyedforworker',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
