# Generated by Django 5.2 on 2025-04-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_alter_pyedforworker_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyedforworker',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='staff',
            name='salary_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
