# Generated by Django 5.2 on 2025-04-17 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_pyedforworker_amount_staff_salary_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='user_auth.student'),
        ),
        migrations.CreateModel(
            name='StudentPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ed', models.DateField(auto_now_add=True)),
                ('updated_ed', models.DateField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('Cr', 'Картой'), ('Mn', 'Наличкой')], max_length=2)),
                ('value', models.CharField(blank=True, max_length=40, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('course_pay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='user_auth.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='user_auth.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Пришел'), ('A', 'Отсутствует'), ('L', 'Опоздал'), ('E', 'Уважительная причина')], max_length=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='user_auth.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='user_auth.student')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
