# Generated by Django 5.2 on 2025-04-23 13:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_group_students_studentpay_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='created_ed',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workday',
            name='updated_ed',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('student', 'Студент'), ('teacher', 'Преподаватель'), ('worker', 'Сотрудник'), ('supervisor', 'Глава')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkerAttandance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ed', models.DateField(auto_now_add=True)),
                ('updated_ed', models.DateField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('P', 'Пришел'), ('A', 'Отсутствует'), ('L', 'Опоздал'), ('E', 'Уважительная причина')], max_length=1)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='user_auth.staff')),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.workday')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
