# Generated by Django 5.2 on 2025-04-23 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0011_studentposition_student_created_ed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students_in_course', to='user_auth.course'),
        ),
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='groups', to='user_auth.student'),
        ),
        migrations.AlterField(
            model_name='grouphomework',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks_for_group', to='user_auth.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(related_name='students_in_group', to='user_auth.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='studenthomework',
            name='group_homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks_in_group', to='user_auth.grouphomework'),
        ),
        migrations.AlterField(
            model_name='studenthomework',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks_submitted', to='user_auth.student'),
        ),
    ]
