# Generated by Django 5.2 on 2025-04-24 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0012_student_courses_alter_group_students_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ed', models.DateField(auto_now_add=True)),
                ('updated_ed', models.DateField(auto_now=True)),
                ('course_level', models.CharField(choices=[('beg', 'Начальный'), ('int', 'Средний'), ('adv', 'Продвинутый')], default='beg', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='student_position',
            field=models.ManyToManyField(related_name='Student_position', to='user_auth.studentposition'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='user_auth.courselevel'),
        ),
    ]
