# Generated by Django 5.2 on 2025-04-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0014_alter_course_course_level_alter_course_mentor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='students_in_course', to='user_auth.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, related_name='students_in_group', to='user_auth.group'),
        ),
    ]
