# Generated by Django 5.2 on 2025-04-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0015_alter_student_courses_alter_student_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_position',
        ),
        migrations.DeleteModel(
            name='StudentPosition',
        ),
        migrations.AddField(
            model_name='student',
            name='student_position',
            field=models.CharField(blank=True, choices=[('active', 'Учится сейчас'), ('end', 'Закончил обучение'), ('left', 'Не закончил и ушёл')], default='active', max_length=15, null=True),
        ),
    ]
