# Generated by Django 5.2 on 2025-04-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0016_remove_student_student_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rom_name',
            field=models.CharField(default='Standard_room', max_length=90),
        ),
    ]
