# Generated by Django 5.2 on 2025-04-24 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0017_room_rom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='rom_numb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_auth.room'),
        ),
    ]
