# Generated by Django 5.2 on 2025-04-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0018_alter_lesson_rom_numb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselevel',
            name='course_level',
            field=models.CharField(choices=[('beg', 'Базовый'), ('int', 'Средний'), ('adv', 'Продвинутый')], default='beg', max_length=3),
        ),
    ]
