# Generated by Django 5.2 on 2025-04-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0020_alter_courselevel_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students_in_course', to='user_auth.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='students_in_group', to='user_auth.group'),
        ),
    ]
