# Generated by Django 5.2 on 2025-04-24 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0021_alter_student_courses_alter_student_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Пришел'), ('A', 'Отсутствует'), ('L', 'Опоздал'), ('E', 'Уважительная причина')], max_length=1)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='user_auth.attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.student')),
            ],
            options={
                'unique_together': {('attendance', 'student')},
            },
        ),
    ]
