# Generated by Django 5.2 on 2025-04-24 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0022_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.group'),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Пришел'), ('A', 'Отсутствует'), ('L', 'Опоздал'), ('E', 'Уважительная причина')], max_length=1)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='user_auth.attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.student')),
            ],
            options={
                'unique_together': {('student', 'attendance')},
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='students',
            field=models.ManyToManyField(through='user_auth.AttendanceRecord', to='user_auth.student'),
        ),
        migrations.DeleteModel(
            name='StudentAttendance',
        ),
    ]
