# Generated by Django 5.2 on 2025-04-24 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0023_alter_attendance_group_attendancerecord_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='user_auth.group'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='students',
            field=models.ManyToManyField(related_name='attendances', through='user_auth.AttendanceRecord', to='user_auth.student'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.attendance'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('attendance', 'student')},
        ),
    ]
