# Generated by Django 5.2 on 2025-04-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0024_alter_attendancerecord_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkerAttandance',
            new_name='WorkerAttendance',
        ),
        migrations.AddField(
            model_name='lesson',
            name='attendance',
            field=models.ManyToManyField(blank=True, related_name='Attendance', to='user_auth.attendance'),
        ),
    ]
